[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
test_ignore = test_native
lib_deps =
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	jgromes/RadioLib@^7.3.0
	mikalhart/TinyGPSPlus@^1.1.0
	jgromes/RadioBoards@^1.0.0

[env:native]
platform = native
test_ignore = test_device
test_build_src = true
debug_test = *
